"""Add AI customization fields to User model

Revision ID: 28f28fee3c5c
Revises: 6b23cc93b785
Create Date: 2025-10-11 03:27:28.161739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f28fee3c5c'
down_revision = '6b23cc93b785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_system_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_tone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('include_ai_signature', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('include_ai_signature')
        batch_op.drop_column('ai_tone')
        batch_op.drop_column('ai_system_prompt')

    # ### end Alembic commands ###
