"""Add sentiment to Message model

Revision ID: 4e51163fce9e
Revises: 8b31f468c0bd
Create Date: 2025-10-05 21:29:39.512938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e51163fce9e'
down_revision = '8b31f468c0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
