"""fixing models

Revision ID: 648a3d1b2578
Revises: 7c53add39184
Create Date: 2025-10-05 21:16:20.149332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648a3d1b2578'
down_revision = '7c53add39184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###
