"""Add subscription_plan and message_count to User model

Revision ID: 784f4138ef8d
Revises: 4e51163fce9e
Create Date: 2025-10-05 21:36:37.779696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784f4138ef8d'
down_revision = '4e51163fce9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    subscriptionplan = sa.Enum('TRIAL', 'BASIC', 'PRO', name='subscriptionplan')
    subscriptionplan.create(op.get_bind())
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', subscriptionplan, nullable=True))
        batch_op.add_column(sa.Column('message_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('message_count')
        batch_op.drop_column('subscription_plan')
    subscriptionplan = sa.Enum('TRIAL', 'BASIC', 'PRO', name='subscriptionplan')
    subscriptionplan.drop(op.get_bind())
    # ### end Alembic commands ###
