"""Add keyword_triggers to User model

Revision ID: 8b31f468c0bd
Revises: e833d4da2b27
Create Date: 2025-10-05 21:26:52.014400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b31f468c0bd'
down_revision = 'e833d4da2b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword_triggers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('keyword_triggers')

    # ### end Alembic commands ###
