"""Add stripe_customer_id field and use full API registration

Revision ID: 98230dde9559
Revises: 
Create Date: 2025-09-15 02:57:58.419434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98230dde9559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
