"""Add signalwire_signing_key to User model

Revision ID: a0db559ac418
Revises: bd95963b306e
Create Date: 2025-10-02 17:31:41.822036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0db559ac418'
down_revision = 'bd95963b306e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signalwire_signing_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('signalwire_signing_key')

    # ### end Alembic commands ###
