"""Add contact_id to Conversation and remove user_id from Message

Revision ID: e833d4da2b27
Revises: 648a3d1b2578
Create Date: 2025-10-05 21:24:32.352463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e833d4da2b27'
down_revision = '648a3d1b2578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('contact_id', sa.Integer(), nullable=True))
    
    # Data migration
    op.execute("""
        INSERT INTO contacts (user_id, phone_number, name, created_at, updated_at)
        SELECT DISTINCT c.user_id, c.contact_number, c.contact_number, NOW(), NOW()
        FROM conversations c
        LEFT JOIN contacts con ON c.user_id = con.user_id AND c.contact_number = con.phone_number
        WHERE con.id IS NULL
    """)

    op.execute("""
        UPDATE conversations
        SET contact_id = contacts.id
        FROM contacts
        WHERE conversations.user_id = contacts.user_id AND conversations.contact_number = contacts.phone_number
    """)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('contact_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_foreign_key('fk_conversations_contacts', 'contacts', ['contact_id'], ['id'])
        batch_op.drop_column('contact_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###
