"""adding to schema

Revision ID: fc00ac51bcf0
Revises: 8771894ec285
Create Date: 2025-09-19 03:01:09.051510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc00ac51bcf0'
down_revision = '8771894ec285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('controlled_by', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('controlled_by')

    # ### end Alembic commands ###
